<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} selected='selected' value=''> </option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='last'}selected='selected'{/if}value="last">last</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='1'}selected='selected'{/if}value="1">1st</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='2'}selected='selected'{/if}value="2">2nd</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='3'}selected='selected'{/if} value="3">3rd</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='4'}selected='selected'{/if} value="4">4th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='5'}selected='selected'{/if} value="5">5th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='6'}selected='selected'{/if} value="6">6th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='7'}selected='selected'{/if} value="7">7th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='8'}selected='selected'{/if} value="8">8th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='9'}selected='selected'{/if} value="9">9th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='10'}selected='selected'{/if} value="10">10th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='11'}selected='selected'{/if} value="11">11th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='12'}selected='selected'{/if} value="12">12th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='13'}selected='selected'{/if} value="13">13th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='14'}selected='selected'{/if} value="14">14th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='15'}selected='selected'{/if} value="15">15th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='16'}selected='selected'{/if} value="16">16th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='17'}selected='selected'{/if} value="17">17th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='18'}selected='selected'{/if} value="18">18th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='19'}selected='selected'{/if} value="19">19th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='20'}selected='selected'{/if} value="20">20th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='21'}selected='selected'{/if} value="21">21st</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='22'}selected='selected'{/if} value="22">22nd</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='23'}selected='selected'{/if} value="23">23rd</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='24'}selected='selected'{/if} value="24">24th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='25'}selected='selected'{/if} value="25">25th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='26'}selected='selected'{/if} value="26">26th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='27'}selected='selected'{/if} value="27">27th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='28'}selected='selected'{/if} value="28">28th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='29'}selected='selected'{/if} value="29">29th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='30'}selected='selected'{/if} value="30">30th</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition.day_of_month) && $repetition.day_of_month =='31'}selected='selected'{/if} value="31">31st</option>