<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} selected='selected'></option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition) && $repetition.month_of_year =='1'}selected='selected' {/if}value="1">January</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition) && $repetition.month_of_year =='2'}selected='selected' {/if}value="2">February</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition) && $repetition.month_of_year =='3'}selected='selected' {/if}value="3">March</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition) && $repetition.month_of_year =='4'}selected='selected' {/if}value="4">April</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition) && $repetition.month_of_year =='5'}selected='selected' {/if}value="5">May</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition) && $repetition.month_of_year =='6'}selected='selected' {/if}value="6">June</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition) && $repetition.month_of_year =='7'}selected='selected' {/if}value="7">July</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition) && $repetition.month_of_year =='8'}selected='selected' {/if}value="8">August</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition) && $repetition.month_of_year =='9'}selected='selected' {/if}value="9">September</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition) && $repetition.month_of_year =='10'}selected='selected' {/if}value="10">October</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition) && $repetition.month_of_year =='11'}selected='selected' {/if}value="11">November</option>
<option {if $smarty.post && $smarty.post['siteSearchForm']['location']['state'] == 'CA'}selected='selected'{/if} {if isset($repetition) && $repetition.month_of_year =='12'}selected='selected' {/if}value="12">December</option>